### ISSUE TITLE
offduty

### ISSUE THREAD

**Issue by xrtw** [renzuzu/renzu_jobs#1]
possible to check off duty members?

police - offpolice and etc

**Comment by renzuzu** [comment]
Will add in todo

**Comment by Srayuch** [comment]
hi , renzuzu " bossmenu action" not deposit  and withdraw where type = "money" Or is it about esx_society

**Comment by renzuzu** [comment]
its not using esx_society
its only grab once and transfer the society money to this script job money.

On Off Duty is Applied.
