### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mistr140** [renzuzu/renzu_jobs#10]
Suggestion: create a version where the weapons will be like items for inventors like this one https://github.com/RuisSoftware/FiveM-Resources/tree/master/ESX/Inventory%20HUD/ESX%20v1.2%20(v1-final)/DP_Inventory

**Comment by renzuzu** [comment]
even if i wanted to support weapons as item.

a lot of inventory script have a different logic of being a weapon as item.
a lot of them does not use ESX loadout.

if you are using ESX >= final and your inventory is not slot based, you should not make the weapon as item!

**Comment by mistr140** [comment]
In my opinion, it would be enough for there to be a change to an item in the config and it would negate weapons but items

**Comment by renzuzu** [comment]
but when getting the data before storing it is not possible if ESX loadout is not being used.

its mean we cant get the data if weapon has a Attachment or not,

making the weapon as item is not the real issue, but the attachments when storing and getting.

its possible but its not worth it, i will destroy the basic function of ESX if i do that 🗡️ 
and in worst case i may need to provide a edited ESX for that, its hassle for all.

**Comment by mistr140** [comment]
It would definitely come in handy, I tried it myself but I didn't succeed

**Comment by renzuzu** [comment]
We can add this as optional.

And supporting items for weapon only

No attachments will be made.

Or we can create a logic that will uninstall all attachments 
to item,

So your attachment system should be item type too

**Comment by mistr140** [comment]
Create it as you see fit, I don't care how badly it will work

**Comment by mistr140** [comment]
Or write me in which file which line recognizes whether it is a weapon or an item and I will delete it and the problem will be solved
