### ISSUE TITLE
Missing images for job vehicles

### ISSUE THREAD

**Issue by peppinoita** [renzuzu/renzu_jobs#11]
Hi renzuzu.

First of all I found you and your github by chance and I'm really impressed how extremely good you and your releases are!
How much passion you put in the scripts and how well written they are!

I was looking for a way to support you in an economical way but I didn't found anything.

After this, here my issue:

I cannot understand how show my custom vehicle picture inside the garage and vehicle shop.

I looked for it everything but I didn't understand why they are not shown. Files are inside the img folder with .png extension and as name the vehicle spawn name.

I'm sure my neurons are fighting to understand but no-one wins...

**Comment by peppinoita** [comment]
Nevermind I found it !  
By the way, can you answer me about the donation part?

**Comment by renzuzu** [comment]
sorry i didnt have a chance to answer your first question,
but seems you fixed it? glad its fixed.

about donation part, thank you but now i dont have anything to receive a donation :(
its fine i will continue this without getting any return
