### ISSUE TITLE
Issues with the vehicleshop and garage.

### ISSUE THREAD

**Issue by classiemoodo** [renzuzu/renzu_jobs#14]
When i wanna buy a vehicle, he tooks the money but nothing happens. The vehicles are not stored in de database and the the popup to buy a vehicle won't close until you run out of money.

**Comment by peppinoita** [comment]
use latest version

**Comment by classiemoodo** [comment]
> use latest version

I do

**Comment by renzuzu** [comment]
is it confirm you are using latest version from main branch (to be sure)

i remember fixing this week ago.

please confirm and send repro steps and server error if theres any

**Comment by classiemoodo** [comment]
Yes i am very sure i use version 1.018 and i get no errors. Its only take the money, the pop-up stays in your screen and you can click so much as you want until your money is gone and then the pop-up disappear and you got a notification that you dont have enough money.

**Comment by classiemoodo** [comment]
I see a error:

[   script:renzu_jobs] SCRIPT ERROR: @renzu_jobs/server.lua:37: attempt to index a nil value (local 'account')
[   script:renzu_jobs] > handler (@esx_addonaccount/server/main.lua:63)
[   script:renzu_jobs] > fn (@renzu_jobs/server.lua:35)
[   script:renzu_jobs] Renzu Jobs LOADED

**Comment by renzuzu** [comment]
set config.useSociety to false
