### ISSUE TITLE
Job creator bug

### ISSUE THREAD

**Issue by mistr140** [renzuzu/renzu_jobs#17]
https://youtu.be/tUu98R0Q5aw

**Comment by renzuzu** [comment]
add the ESX code to your esx framework

**Comment by mistr140** [comment]
> 
> 
> add the ESX code to your esx framework
> (this is only tested in ESX legacy)

Im have in server.lua

**Comment by mistr140** [comment]
Error 
![obrazek](https://user-images.githubusercontent.com/43046423/134813182-9efbc164-d9c5-42f1-a245-dd5773537ed0.png)
