### ISSUE TITLE
Paycheck issue (strange behaviour)

### ISSUE THREAD

**Issue by peppinoita** [renzuzu/renzu_jobs#18]
Hi again.

I'm facing a very strange issue regarding paycheck.

The default jobs (police, mechanic, ambulance) do not get paycheck (the company is too poor ...) probably because the addon_account_data is 0.

Instead the custom added jobs always get the paycheck even if addon_account_data is 0 and company money on renzu_jobs table is 0 and if there are some money, they are not decreased on paycheck event.

Do you have some suggestion on how modify the paycheck.lua file in order to works only with renzu_jobs?

**Comment by renzuzu** [comment]
what paycheck script?
you need to add the exports of remove or add money from renzu_jobs to your paycheckscript.

i may add a paycheck system here (asap) if its really needed to avoid hassle to any ends

or continue using other paycheck script but you need to implement it your self using the exports.

Thank you

**Comment by peppinoita** [comment]
I use the standard esx paycheck

**Comment by renzuzu** [comment]
i added files needed for paycheck
https://github.com/renzuzu/renzu_jobs/commit/81fb696e60dc7a4dd91614c5466f7212917024c2
its on es_extended folder

a custom paycheck.lua for esx legacy and older version.
to use the job money here
