### ISSUE TITLE
in esx 1.1 it doesn't respect the item limit

### ISSUE THREAD

**Issue by Tnnuy-sv** [renzuzu/renzu_jobs#19]
can you adapt to esx 1.1 so it sees the limit instead of weight?
Tks

**Comment by renzuzu** [comment]
This will not work 100% in 1.1 
Setbonus to empoyee
Black money compatibility

Which part is the problem with limit?

**Comment by Tnnuy-sv** [comment]
in esx 1.1 it works by limit, if i limit 1/1, i can buy or craft unlimited items in the inventory

**Comment by renzuzu** [comment]
Im thinking but not sure if its worth it.

Why you guys not upgrading atleast to final?
No offense question.

If answer is reasonable. I can make this fully backward compatible with esx 1.1

**Comment by renzuzu** [comment]
try using the latest main branch (not the release)
https://github.com/renzuzu/renzu_jobs/commit/1b860367bfc5c2c06ab8bf9643ec6bcdfdfa4db5
compatibility with some ESX 1.1 tel me whats missing ill add it

**Comment by Tnnuy-sv** [comment]
I tried using the final version but some scripts from my server do not work.. I was going to lose months of setting up my server and the accounts of the players.. Your scripts are fantastic, I really liked this script.. He and full has warehouse stores, weapons, craft, in addition to everything you made a beautiful and friendly interface, I am grateful for you put it compatible.. I'm going to put it on my server and see if everything works... Thank you very much

**Comment by renzuzu** [comment]
yea i do put some compatibility with esx 1.1 money logic

let me know if theres anything you need to port from 1.1 to current ver.

i cant test as i dont have 1.1 esx atm..

**Comment by renzuzu** [comment]
i have pushed an update regarding esx 1.1 again.
https://github.com/renzuzu/renzu_jobs/commit/bf1d61caf70cbfdf306d766d3ef23e53352aeaa4
addmoneyoffline fix

**Comment by Tnnuy-sv** [comment]
there is a problem with the inventories.. when you tried to add and the inventory is full, the item disappears from the job's inventory

**Comment by renzuzu** [comment]
Looks like the problem is 1.1 does not have 
xPlayer.addWeaponAmmo

I will try to patch this asap
This will fixed both problem

Thanks for being helpful

**Comment by Tnnuy-sv** [comment]
when you get it corrected, let me know
Thanks

**Comment by renzuzu** [comment]
Yes in few hours i just woke up buddy hehe

**Comment by Tnnuy-sv** [comment]
Do you have a discord ?

**Comment by renzuzu** [comment]
message me in CFX i cant post it here.

fixed https://github.com/renzuzu/renzu_jobs/commit/0d5957d1eb2f05cf8dfb7712beb1cdb81a94b375
weapon ammo.

if you found any error in esx 1.1 tell me.

**Comment by Tnnuy-sv** [comment]
no longer doubling to weapons!

in the store that has food and water and a pistol, it's wrong if I try to buy the pistol! when the inventory has no space and we try to take the items out of the work inventory

**Comment by Tnnuy-sv** [comment]
thanks for all the help given to support this script for esx 1.1 !!
