### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mistr140** [renzuzu/renzu_jobs#20]
Hi intraction menu not work. Video: https://youtu.be/U-6ykdlm9L8

How im can edit how job use this and how open this menu
![obrazek](https://user-images.githubusercontent.com/43046423/135319795-33859a5a-c9e7-41aa-827b-c46f86228820.png)

**Comment by renzuzu** [comment]
This is adv usage only for now.

You need to check if you have jsfouridcard

This interaction menu is sample only

You have to setup it to fit your needs

Read the readme in github page to understand how to use it

**Comment by mistr140** [comment]
so if I understand correctly I have to enter it directly into the police job renzu_jobs can't do it alone.

You can send me a sample job because I didn't understand much about it

**Comment by renzuzu** [comment]
No you can use the plugin folder to upload custom files

Ofcourse you need to mannually do this all

Thats why this is marked as adv usage only for now.
My original plan is to make all interaction in config provided in plugin folder

But i do not have time yet to add more lua files for each interaction
