### ISSUE TITLE
Police Store not working.

### ISSUE THREAD

**Issue by planeklm** [renzuzu/renzu_jobs#23]
Hello,
I have not got the police store to work yet, this video will show you,
https://streamable.com/v0usn7

**Comment by renzuzu** [comment]
show me server console after buying

**Comment by planeklm** [comment]
![12313](https://user-images.githubusercontent.com/91488137/135723653-1ebed9b2-2fd3-4566-99fb-bf8d57b6a68e.PNG)

**Comment by renzuzu** [comment]
replace this with mysql-async
![image](https://user-images.githubusercontent.com/82306584/135727485-cd3dd0e4-5c93-4245-9821-fbe9bd1a8609.png)

**Comment by planeklm** [comment]
Thanks!
