### ISSUE TITLE
Inventory issue

### ISSUE THREAD

**Issue by Jonneis** [renzuzu/renzu_jobs#3]
There is a weird issue with the inventory function, when you open the menu to deposit items they appear only the items that you have on the quick slot (1,2,3,4,5) not in the whole inventory plus you can see 2 types of black money idk why.

https://i.gyazo.com/83c59fe3f90999de9c6a18e5677c6d42.mp4

(p.s: i use inventory with money and weapons as an items and legacy version)

**Comment by renzuzu** [comment]
what inventory are you using?

is the inventory store or use xPlayer.inventory ?

i am using legacy too, but this might something to do with your current inventory.
about black money did you turn on the config.black_money_item?

**Comment by renzuzu** [comment]
i just look if this is linden_inventory
i will not support it.

if i will have to support this will break the STANDARD of ESX it self.

just disable the inventory in this script and use the stash system from linden itself.

**Comment by Jonneis** [comment]
Yes is linden's i just notice i have to change everything to make it work so yeah is better the stash option thanks though.
