### ISSUE TITLE
Unable to set Job

### ISSUE THREAD

**Issue by HiIchBinFlo** [renzuzu/renzu_jobs#35]
Its not possible to set a Job. 
Error in Console: 
[   script:renzu_jobs] SCRIPT ERROR: @renzu_jobs/server.lua:591: attempt to index a nil value (field '?')
[   script:renzu_jobs] > TriggerServerCallback (@es_extended/server/functions.lua:33)
[   script:renzu_jobs] > handler (@es_extended/server/common.lua:88)

**Comment by Seth2210** [comment]
> Nop I just create it throguh the databse

did u fix it?
