### ISSUE TITLE
[ISSUE] Menu not closing on fail

### ISSUE THREAD

**Issue by MrNewb** [renzuzu/renzu_jobs#4]
https://streamable.com/3jc6ke

When a player does not have enough money the menu gets stuck, going to another spot can close it though.

**Comment by MrNewb** [comment]
additionally commenting things out in the config like the armory breaks the script for me.
example ---
        -- ['weapon_armory'] = { -- DISABLE weapon armory?
        --     grade = 0, -- minimum job grade can access this feature
        --     coord = vector3(461.57052612305,-983.02404785156,30.689599990845),
        --     label = 'Weapon Armory',
        --     event = 'renzu_jobs:openweapons',
        -- },

is fine but 

        -- ['shop'] = {
        --    [1] = {
        --        webhook = false, -- change this to your webhook link, if this a false, its mean no loggin at all, ex. 'https://discord.com/api/webhooks/883246462****'
        --        public = false, -- if shop is public or for this job only. (income money will go to this job money)
        --        grade = 0, -- minimum job grade can access this feature,
        --        ['items'] = {
        --            [1] = {name = 'bread', label = 'Bread', value = 50},
        --            [2] = {name = 'water', label = 'Water', value = false}, -- if false its free
        --            [3] = {name = 'WEAPON_PISTOL', label = 'Pistol', value = 15000}, -- use capitalize for weapon to avoid bugs
        --        },
        --        label = 'Police Shop 1',
        --        coord = vector3(452.42401123047,-980.31774902344,30.689605712891),
        --        event = 'renzu_jobs:openshop',
        --    },
        --    [2] = {
        --        webhook = false, -- change this to your webhook link, if this a false, its mean no loggin at all, ex. 'https://discord.com/api/webhooks/883246462****'
        --        public = true, -- if shop is public or for this job only. (income money will go to this job money)
        --        grade = 0, -- minimum job grade can access this feature
        --        ['items'] = {
        --            [1] = {name = 'bread', label = 'Bread', value = 50},
        --            [2] = {name = 'water', label = 'Water', value = false}, -- if false its free
        --            [3] = {name = 'WEAPON_PISTOL', label = 'PISTOL', value = 15000}, -- use capitalize for weapon to avoid bugs
        --        },
        --        label = 'Police Shop 2',
        --        coord = vector3(436.20028686523,-986.38391113281,30.689611434937),
        --        event = 'renzu_jobs:openshop',
        --    },
        --},

gives this error
"Script error: @renzu_jobs/client.lua502: bad argument #1 for 'for iterator' (table expected, got nil)
fn (@ranzu_jobs/client.lua:502)

Going offduty on police is giving  Ignoring invalid .setJob() usage for "char1:123456789213456789456789"
Could be the way its done with esx_multicharacter? 


[Suggestions]
Could you add mythic notify to the config?
could you add support for linden_inventory? *weapons as items* are in this

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_jobs/commit/3a5dbd1821370b15c44904c8b6023f5727bba5b0

Fixed shop error and if not enough money , shopmenu should be closing.
uncommenting the armory should not broke script.
does the offjob DB is not default on esx police job?
yes multi character should be not a problem because once you loaded, job is different again.
Mythic notify.. i will try, you could do it your self, replace all renzu_notify events
whats the use case of progbars?

and about weapon as items. its not possible right now, this script aim to support STANDARD of ESX xPlayer Functions for now.

**Comment by MrNewb** [comment]
policejob default is only 0-4,  Ive replaced the events or at least most so far just a suggestion for others. And as far as progressbars It looked like the crafting does it through your popui but ive been switching most of that over to mythic so no additional resources need to be added. Ty for fixing the shop error :) you do cool work, have you thought about making a discord so snippets/edits may be shared?
