### ISSUE TITLE
Bug: F6 Menu Cuff

### ISSUE THREAD

**Issue by robert4049** [renzuzu/renzu_jobs#41]
When I use the included Cuffing Script and go to cuff another player it cuffs myself? 

Repro: add the server side cuff into the citizen interaction, look at another player, press f6 and cuff.

**Comment by renzuzu** [comment]
The script only setup the menu with trigger events

Cuff issue is from your cuff script or police job

Your interaction to other player must always like this

Get player id of nearest player
And send it along with the events
