### ISSUE TITLE
job shop error

### ISSUE THREAD

**Issue by georgekris** [renzuzu/renzu_jobs#43]
hi . i make this job shop and i set a shop open to everyone if i have no job i can buy from this shop but if i have what ever job i can’t buy anything and i get this error.

[ script:renzu_jobs] SCRIPT ERROR: @renzu_jobs/server.lua:492: attempt to index a nil value (field ‘shop’)
[ script:renzu_jobs] > TriggerServerCallback (@es_extended/server/functions.lua:160)
[ script:renzu_jobs] > handler (@es_extended/server/common.lua:71)
[ script:renzu_jobs] SCRIPT ERROR: @renzu_jobs/server.lua:492: attempt to index a nil value 
(field ‘shop’)
[https://imgur.com/a/eYwP6hp](url)

**Comment by HiIchBinFlo** [comment]
Same issue, did you find a fix?
