### ISSUE TITLE
Duplicate money and other items 

### ISSUE THREAD

**Issue by BigYoo93** [renzuzu/renzu_jobs#46]
When we put something in stash and want to get out when write amount and spam withdraw button then we can duplicate amount

**Comment by Velkostatkar** [comment]
I am sure this will be fixed when will be released full compatibility with ox_inventory

**Comment by BigYoo93** [comment]
i use MF-Inventory so i need other solution :/

**Comment by Velkostatkar** [comment]
you can put there some Wait mathrandom or you can put a part of code where say check if is stash open by another player send notifiy you cant enter stash becouse is in use be another player
