### ISSUE TITLE
Shop limit

### ISSUE THREAD

**Issue by Dejvi1** [renzuzu/renzu_jobs#47]
Hi there for bread and water works all good for weapons aswell. But when i add another items lets say clip for gun it says that i dont have space in inventory...
Is there any limit i can set ? im using 1.1 aswell set in cfg..
Item limit in sql is 20

**Comment by Velkostatkar** [comment]
By my opinion you using old version of SQL limit, modern is WEIGHT.

But somehow limit still working even in WEIGHT based scripts. so set that (your LIMIT) to 1 becouse the script whink its WEIGHT 20 so solution is in DB set all items you have problem to LIMIT 1.

Most important thing is that if you are using this old system you will have more and more problems with more scripts, so please update your server minimaly to WEIGHT BASE.
