### ISSUE TITLE
cant buy car

### ISSUE THREAD

**Issue by colector-user** [renzuzu/renzu_jobs#6]
cant buy weapon and car cant store weapon  its give me error 
![we](https://user-images.githubusercontent.com/71615541/132591145-38e60d8c-ca8e-442d-862d-9e90b116e2ed.png)

**Comment by colector-user** [comment]
cant open boss action

**Comment by colector-user** [comment]
when i buy car his take money but not give me a car not found in garage

**Comment by colector-user** [comment]
i set all job grade 0

**Comment by colector-user** [comment]
i use ESX LEGACY

**Comment by colector-user** [comment]
water bread other item is fine insted this thinks

**Comment by renzuzu** [comment]
Export the sql and install a real esx legacy

Hasweapon function ia not in esx legacy???
