### ISSUE TITLE
use esx_Society not fonctionary

### ISSUE THREAD

**Issue by dim62** [renzuzu/renzu_jobs#64]
![image](https://user-images.githubusercontent.com/91420869/169327974-ccf2c905-6bf6-484e-8027-dfbe71fab138.png)

**Comment by Gold14567** [comment]
i found a solution for it you gonna open your server.lua and replace all the account with Account

**Comment by Gold14567** [comment]
[server.txt](https://github.com/renzuzu/renzu_jobs/files/9646013/server.txt)
