### ISSUE TITLE
error  global DrawMarkerInput

### ISSUE THREAD

**Issue by dim62** [renzuzu/renzu_jobs#66]
![image](https://user-images.githubusercontent.com/91420869/195345642-9c4f5707-f4ee-4dda-8b6b-e6b3ab8a1a6b.png)

**Comment by renzuzu** [comment]
drawmarker input is deprecated i forgot to remove it.
ill fix this on next patch

**Comment by dim62** [comment]
when are you going to update renzu_jobs i'm excited to finish my jobs
