### ISSUE TITLE
no blips after update

### ISSUE THREAD

**Issue by TheOnlyNecro** [renzuzu/renzu_jobs#67]
I have no blips anywhere for any job associated with this script since I updated it. Also I had a player crash with the error Reliable network event size overflow:renzu_job:updatejob

**Comment by TheOnlyNecro** [comment]
Sorry I ment the markers are missing, all markers for everything, boss menus dressing room everything is missing

**Comment by TheOnlyNecro** [comment]
['police'] = {
        ['max_salary'] = 5000, -- maximum ammount of salary can be changed from boss action
        ['bossmenu'] = {
            webhook = false, -- change this to your webhook link, if this a false, its mean no loggin at all, ex. 'https://discord.com/api/webhooks/883246462****'
            grade = 8, -- minimum grade to access
            coord = vector3(462.1034, -985.5555, 30.7281),
            label = 'Boss Action',
            event = 'renzu_jobs:openbossmenu',

When I goto the coords with job grade there is no marker I cannot access the police boss menu or inventory

**Comment by renzuzu** [comment]
Are you refering to maim branch?
Its uses ox lib now

If you dont have oxlib this resource wont work
