### ISSUE TITLE
erreur account + paycheck

### ISSUE THREAD

**Issue by dim62** [renzuzu/renzu_jobs#68]
money is not deducted from the company
paycheck 
es_extended version '1.8.5'

[script:esx_addonacco] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @renzu_jobs/server.lua:42: attempt to index a nil value (local 'account')
[script:esx_addonacco] > ref (@renzu_jobs/server.lua:42)
[script:esx_addonacco] > <unknown> (@oxmysql/dist/build.js:22233)
[script:esx_addonacco] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:esx_addonacco] > async rawQuery (@oxmysql/dist/build.js:22223)
[script:esx_addonacco] 
[script:esx_addonacco] > handler (@esx_addonaccount/server/main.lua:52)
[script:esx_addonacco] > <unknown> (@oxmysql/dist/build.js:22233)
[script:esx_addonacco] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:esx_addonacco] > async rawQuery (@oxmysql/dist/build.js:22223)
------------------------------------------------------------------
it works but returns account = nil

**Comment by renzuzu** [comment]
this is the esx society thing. that convert society money to this resource money.

i have removed this as its old, it could be probably break changes from newer version of society.

**Comment by dim62** [comment]
es_extended version '1.8.5'
paycheck legacy 

[   script:renzu_jobs] SCRIPT ERROR: @renzu_jobs/server.lua:53: attempt to index a nil value (field 'FreePaycheck')
[   script:renzu_jobs] > [global chunk] (@renzu_jobs/server.lua:53)
[   script:renzu_jobs] > fn (@es_extended/server/paycheck.lua:71)
[  script:es_extended] SCRIPT ERROR: @es_extended/server/paycheck.lua:71: 
[  script:es_extended]  An error occurred while calling export `JobMoney` in resource `renzu_jobs`:
[  script:es_extended] 
[  script:es_extended]  ---

**Comment by dim62** [comment]
I put back the system (FreePaycheck) and it works 
config.FreePaycheck = {
    ['ambulance'] = true,
    ['police'] = true
}
do you have a solution for esx_billing or add a renzu_jobs bills for oxtarget ? or a renzu_billing
