### ISSUE TITLE
duplicate weapons

### ISSUE THREAD

**Issue by kielerboy** [renzuzu/renzu_jobs#7]
hello i have found a bug when i store a weapon and remove it again it does not remove it from the storage and you can always take it out and duplicate the weapon

here is the video off the problem  

https://youtu.be/ZYpu8E77ukM

**Comment by renzuzu** [comment]
How to repro this?

Esx version

Item weapon?

Custom weapon system?

Because using normal esx legacy or final does not reporduce this dupe

**Comment by kielerboy** [comment]
How to repro this? :  see the video above

Esx version  1.1.0

Item weapon?   no its normal esx weapon system like giveweapon event

Custom weapon system?    no

**Comment by renzuzu** [comment]
I will check and install a 1.1 esx

This need essential mode right

Ill get back to you 

Thanks for giving insight info

**Comment by renzuzu** [comment]
esx 1.1 is not supported right now
only esx with accounts in users table

**Comment by kielerboy** [comment]
ok but we have esx with accounts in users table https://i.imgur.com/9To7K6B.png

but thank you very much for the help
