### ISSUE TITLE
Wont get money from Selling clothes

### ISSUE THREAD

**Issue by SeraphimGER** [renzuzu/renzu_jobs#71]
im using renzu_clothing and in config everything is right
created a new job with society money in database and job and jobgrades using the comands from renzu_jobs
but now when i buy clothes nothing is on society.
how can i fix that?

Also i got this error in database
![Screenshot_137](https://user-images.githubusercontent.com/98034176/204181047-29c65a2b-73cd-4064-a8b6-a67b3d075c90.png)

thanks for help, and thanks for the scripts <3

**Comment by renzuzu** [comment]
you can resolve it by adding name column
this is a compatibility with lower esx version.

soon i will remove to support lower esx.

**Comment by SeraphimGER** [comment]
ok i will try it thanks
