### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by dim62** [renzuzu/renzu_jobs#73]
have the possibility to buy companies like renzu_shops

**Comment by renzuzu** [comment]
whats the purpose?

when you say buy companies , it will be the same as renzu_shops.

this resource is job management only..but if you explain your use cases. we can think someway

**Comment by dim62** [comment]
> quel est le but?
> 
> quand vous dites acheter des entreprises, ce sera la même chose que renzu_shops.
> 
> cette ressource concerne uniquement la gestion des tâches... mais si vous expliquez vos cas d'utilisation. nous pouvons penser d'une manière ou d'une autre

I think that in life we should buy a building to work example of mechanic the demand and to let a little more free the players example.

I can buy the bennys for 100 000
I become the boss of the bennys by being a mechanic (bennys) 
I can craft, farm, etc.

for example the engine_adder, t20, sultan are bought via renzu_shop they are delivered by the joureus and the mechanic who has access to the store can make or not the repair.

without having to call on the staff so that the players are free to buy or sell their company (without going through the staff)
so we could create several garage bennys, lscustom, hayes, etc.
for state jobs like police, ambulance, manage by the staff

**Comment by renzuzu** [comment]
this is like buying the whole job access.
when you buy the aka benny, you will become the boss.

most servers assign the Boss to each department, i dont think this is a good idea.
