### ISSUE TITLE
Support Default ESX Jobs Interactions Events from ex. esx_policejob and etc.

### ISSUE THREAD

**Issue by SR1FT** [renzuzu/renzu_jobs#74]
My interaction menu doesn't work, it will show up if I press F6 but if I try to search for somebody or hand cuff, then nothing happens. Can you help me?

**Comment by SR1FT** [comment]
![image](https://user-images.githubusercontent.com/120251805/206851533-70eba836-fcd9-4c15-9a43-1ab2e86c67ec.png)

**Comment by renzuzu** [comment]
interaction is advanced method, you need to edit it to use your existing events from ex. police job resource.
