### ISSUE TITLE
renzu_shield

### ISSUE THREAD

**Issue by Skybrick** [renzuzu/renzu_jobs#78]
Hello Renzu. First say that I really like your scripts and then ask you where I can find that "renzu_shield" dependency since I don't have it and it gives me an error. 

[    c-scripting-core] Creating script environments for renzu_jobs
[    c-scripting-core] Failed to load script @renzu_shield/init.lua.
[ citizen-server-impl] Started resource renzu_jobs

Thanks for your time and for making good scripts

**Comment by Matuuu96** [comment]
Same problem.

**Comment by 2Wavyy** [comment]
Hey guys do you remember what was causing this?
