### ISSUE TITLE
Marker support 

### ISSUE THREAD

**Issue by hasidu** [renzuzu/renzu_jobs#80]
Hey renzu i am wondering if there is any possibility to add markers for the points if not for players dont know where to find the positions

**Comment by Visloczki** [comment]
Hello, Maybe can this help for you. 

Place in the client.lua inside to 582 line . Before declare the sphare local variable .
`   local points = lib.points.new(GetEntityCoords(PlayerPedId()), 5, {})

    function points:nearby()
        DrawMarker(2, coord.x, coord.y, coord.z, 0.0, 0.0, 0.0, 0.0, 180.0, 0.0, 1.0, 1.0, 1.0, 200, 20, 20, 50, false, true, 2, nil, nil, false)
    end`

**Comment by hasidu** [comment]
> Hello, Maybe can this help for you.
> 
> Place in the client.lua inside to 582 line . Before declare the sphare local variable . `local points = lib.points.new(GetEntityCoords(PlayerPedId()), 5, {})` `function points:nearby() DrawMarker(2, coord.x, coord.y, coord.z, 0.0, 0.0, 0.0, 0.0, 180.0, 0.0, 1.0, 1.0, 1.0, 200, 20, 20, 50, false, true, 2, nil, nil, false) end`

hi thank youu
