### ISSUE TITLE
[IMPORTANT] INTERACTION ADDING

### ISSUE THREAD

**Issue by hasidu** [renzuzu/renzu_jobs#82]
Hi renzu i tried lot of time to put some interactions from police job etc 
but for example cuff it doesn't cuff players its cuff me and id check show me only my id 
and there was other problems interaction menu 

so i want to ask you if there any possibility that you can intrgate some of them to script like cuff, drag etc .. so players can easily add them in to job they need ?

like on job creator script that paid script has them integrated

below i will leave my cuff client script 

https://pastebin.com/dq3fAy8n

**Comment by hasidu** [comment]
thank you renzu for support

**Comment by hasidu** [comment]
anything ?

**Comment by TheOnlyNecro** [comment]
He never responds.

**Comment by renzuzu** [comment]
sorry but this is a server developer job , the config is alreadyfriendly imo.
you just need to setup the event trigger and names etc.. for each citizen job.
