### ISSUE TITLE
inventory

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_jobs#90]
if mag lagay sa police armory example nag lagay ako sa police armory ng 1 money then pag inopen ko yung personal stash nandon din sya, kaya ba sya na public stash yung police armory then yung personal stash is for isang citizen lang like hindi nakikita ng ibang citizen yung laman then pag naglagay sa police armory dapat hindi din lalagay sa personal stash

**Comment by renzuzu** [comment]
this seems invalid.
my case items from stash and personal inventory is unique.
